export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOAD_COUNTRIES = 'LOAD_COUNTRIES';
export const LOAD_COUNTRIES_ERROR = 'LOAD_COUNTRIES_ERROR';
export const LOADING_COUNTRIES = 'LOADING_COUNTRIES';

export const LOAD_COUNTRY = 'LOAD_COUNTRY';
export const LOAD_COUNTRY_ERROR = 'LOAD_COUNTRY_ERROR';
export const LOADING_COUNTRY = 'LOADING_COUNTRY';